# Array operations with NumPy

In this notebook we are going to learn how to work with array NumPy
- Element wise operations
- Broadcasting
- Comparison with Python Lists

## Element wise operations

In [2]:
import numpy as np

In [3]:
a_array = np.array([1, 2, 3, 4])
b_array = np.array([10, 20, 30, 40])

print(a_array)
print(b_array)

[1 2 3 4]
[10 20 30 40]


In [8]:
# element wise operation
print(a_array + b_array)
print(a_array - b_array)
print(a_array * b_array)
print(a_array / b_array)
print(a_array ** 2)
print(np.sqrt(a_array)) # square root using methos

[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[0.1 0.1 0.1 0.1]
[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]


## Broadcasting

Broadcasting allows operations between arrays that have different shapes.
NumPy automatically expands to arrays when possible

NumPy automatically expands arrays when possible

In [11]:
my_array = np.array([1, 2, 3, 4, 5])
print(my_array + 10)

[11 12 13 14 15]


Comparison python lists with numpy arrays

In [14]:
import time

 

size = 1_000_0000

 

# Python list

L = list(range(size))

start = time.time()

L2 = [x * 2 for x in L]

print("Python list time:", time.time() - start)

 

# NumPy array

A = np.arange(size)

start = time.time()

A2 = A * 2

print("NumPy array time:", time.time() - start)

Python list time: 0.8446283340454102
NumPy array time: 0.05070924758911133
