# Numpy Intro

In [6]:
print("Hello world")

Hello world


In [11]:
import numpy as np

Create a list of numbers

In [12]:
numbers = [1, 2, 3, 4]

In [13]:
array = np.array(numbers)

In [15]:
doubled = array *2
print(doubled)

[2 4 6 8]


Built in array creation!

In [17]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
ones = np.ones((3))
print (ones)

[1. 1. 1.]


In [22]:
range_array = np.arange(0,10,2)
print(range_array)

[0 2 4 6 8]


Indexing and slicing

In [26]:
arr = np.array([20, 30, 40, 50, 60])
#Indexing
print(arr[0],arr[-1])

#slicing
print(arr[0:3])
print(arr[::])

20 60
[20 30 40]
[20 30 40 50 60]


In [28]:
two_d_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_d_array[0,1])


2


In [31]:
print(two_d_array[1,:1])

[4]


## Array Attribute

In [34]:
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
print(arr.shape) # to see the shape of the array

(3, 4)


In [36]:
print(arr.ndim) # to know if it is 2 dimentional or 3 dimentional

2


In [37]:
print(arr.dtype) # to check datatype

int64


In [38]:
print(arr.size) # to check the size

12


### Slicing and Reshaping array

In [40]:
arr = np.arange(1, 13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [46]:
arr_reshaped = arr.reshape(3,4)
print(arr)
print(arr_reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [47]:
arr = np.arange(1, 13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [49]:
reshaped = arr.reshape(4,3)
print(reshaped)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [57]:
extract = reshaped[1:3]
print(extract)

[[4 5 6]
 [7 8 9]]


In [58]:
# Flatten a multi-dimensional array
flattened_arr = reshaped.ravel()
print(flattened_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
