# Numpy Statistical functions and random module

In [2]:
import numpy as np

In [8]:
# Random integers.
dice = np.random.randint(1, 7, size = 10) # 10 dice rolls
print("Dice Rolls ", dice)

# Random floats.
random_floats = np.random.rand(5) # random floats
print("Dice Rolls ", random_floats)

# Random normal distribution.
normal_sample = np.random.randn(5) # mean 0
print("Dice Rolls ", normal_sample)


Dice Rolls  [4 3 3 1 6 2 6 5 1 3]
Dice Rolls  [0.79345271 0.97848838 0.63914558 0.01758532 0.20170083]
Dice Rolls  [ 1.02853383 -0.58259496 -0.33432443 -0.10431221  1.23459523]


# Statistical function

# Numpy makes statistical calculation easy!

In [10]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard deviation:", np.std(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))

Sum: 55
Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Minimum: 1
Maximum: 10


In [11]:
data_2d = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

print("Sum:", np.sum(data_2d))
print("Mean:", np.mean(data_2d))
print("Median:", np.median(data_2d))
print("Standard deviation:", np.std(data_2d))
print("Minimum:", np.min(data_2d))
print("Maximum:", np.max(data_2d))

Sum: 210
Mean: 10.5
Median: 10.5
Standard deviation: 5.766281297335398
Minimum: 1
Maximum: 20


# Reshaping and Stacking arrays

In [14]:
# Reshape
arr_1 = np.arange(12)
print(arr_1)

arr_2 = arr_1.reshape(3,4)
print(arr_2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Stacking arrays

In [17]:
stack1 = np.array([1,2,3])
stack2 = np.array([4,5,6])
vstack = np.vstack([stack1, stack2]) # vertical stacking
hstack = np.hstack([stack1, stack2]) # horizontal stacking
print (vstack, hstack)


[[1 2 3]
 [4 5 6]] [1 2 3 4 5 6]
