In [1]:
import numpy as np

# 3d array

In [2]:
arr3d = np.array([[[1,2,3], [4, 5,6]], [[7,8,9], [10,11,12]]])
print (arr3d)
arr3d.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

# Iteration through arrays

In [10]:
arr1 = np.array ([1, 2, 3, 4, 5])
for array in arr1:
    print( num)

5
5
5
5
5
